### ISSUE TITLE
Unit tests not running during GitHub workflow build stage 

### ISSUE THREAD

**Issue by Hexman768** [ucmo-cs/F24_Avengers#10]
### Description 
* The unit tests that have been written are not being ran during the build stage of the GitHub workflow that was added to the project. 

### Possible Solution 
* I have seen online that this issue can be resolved by removing an existing junit dependency and adding another.

**Comment by michaelharlow** [comment]
From looking at the script it seems to running the tests fine. However, it's actually running the tests twice (the second) isn't displayed however, and doing several other steps we don't really need.

This appears to be because **mvn install** & **mvn package** are both being run which both run the tests and do several build steps we don't need. I will fix the script and separate out the building step and testing step.
